### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by vlerenc** [gardener/monitoring#4]
Some weeks ago, we compiled a list of dashboards improvements that seem sensible:
* [ ] Let's add a KCM dashboard (we have CCM, MCM, etc. but no KCM dashboard so far)
* [ ] Users could get access to K8s DaemonSets/StatefulSets/Deployments/Pods (filtered by shoot cluster resources only)
* [ ] Users should get access to CCM, MCM, and the new KCM dashboards (ideally without resource usage, even if the dashboards then look empty, but CCM and possible KCM only look empty because some other insightful metrics that for instance MCM features are not yet shown there).
* [ ] User should get access to the CoreDNS dashboard (as-is)
* [ ] The nodes dashboard should also show the inodes as a metric that is eviction-relevant
* [ ] Prometheus lacks the CPU throttling information on Kubelet and the container runtime (see also issue https://github.com/gardener/gardener/issues/2800) and when we have it, we should add it to the nodes dashboard system components
* [ ] The pods dashboard should feature CPU throttling information ideally, as well

**Comment by vlerenc** [comment]
It may make sense to combine this ticket with https://github.com/gardener/gardener/issues/2815.

**Comment by wyb1** [comment]
- [ ] Let's add a KCM dashboard (we have CCM, MCM, etc. but no KCM dashboard so far)
- [ ] Users could get access to K8s DaemonSets/StatefulSets/Deployments/Pods (filtered by shoot cluster resources only)
- [ ] Users should get access to CCM, MCM, and the new KCM dashboards (ideally without resource usage, even if the dashboards then look empty, but CCM and possible KCM only look empty because some other insightful metrics that for instance MCM features are not yet shown there).
- [ ] User should get access to the CoreDNS dashboard (as-is)
- [ ] The nodes dashboard should also show the inodes as a metric that is eviction-relevant
- [ ] Prometheus lacks the CPU throttling information on Kubelet and the container runtime (see also issue gardener/gardener#2800) and when we have it, we should add it to the nodes dashboard system components
- [ ] The pods dashboard should feature CPU throttling information ideally, as well

Copied task list since I cannot check the boxes

**Comment by wyb1** [comment]
Many of these items have been completed. If new improvements are required we can create a new issue
